FROM nginx

EXPOSE 80
VOLUME C:/Users/Antonio/Desktop/Ynov/DevOps/DevOps/TP_DOCKER_1/html/index.html

RUN cp  /C:/Users/Antonio/Desktop/Ynov/DevOps/DevOps/TP_DOCKER_1/html/index.html /usr/share/nginx/html
